### ISSUE TITLE
client method called on the server

### ISSUE THREAD

**Issue by hunter688** [Fexcraft/FlansMod#20]
<pre>
[21:51:03] [Server thread/WARN]: Failed to handle packet for /162.12.24.19:33798
net.minecraft.util.ReportedException: Ticking player
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:380) ~[lu.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:162) ~[me.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:213) ~[NetworkDispatcher$1.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287) ~[eo.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [md.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:732) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/Minecraft
        at com.flansmod.common.guns.ItemGun.func_77663_a(ItemGun.java:791) ~[ItemGun.class:?]
        at net.minecraft.item.ItemStack.func_77945_a(ItemStack.java:441) ~[adz.class:?]
        at net.minecraft.entity.player.InventoryPlayer.func_70429_k(InventoryPlayer.java:344) ~[zr.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:510) ~[zs.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2013) ~[sf.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:233) ~[zs.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:303) ~[lu.class:?]
        ... 9 more
> Nov 10, 2016 9:51:03 PM io.netty.util.concurrent.DefaultPromise notifyListener0
WARNING: An exception was thrown by net.minecraft.network.NetworkSystem$7.operationComplete()
io.netty.util.concurrent.BlockingOperationException: DefaultChannelPromise@7264b350(uncancellable)
        at io.netty.util.concurrent.DefaultPromise.checkDeadLock(DefaultPromise.java:390)
        at io.netty.channel.DefaultChannelPromise.checkDeadLock(DefaultChannelPromise.java:157)
        at io.netty.util.concurrent.DefaultPromise.awaitUninterruptibly(DefaultPromise.java:283)
        at io.netty.channel.DefaultChannelPromise.awaitUninterruptibly(DefaultChannelPromise.java:135)
        at io.netty.channel.DefaultChannelPromise.awaitUninterruptibly(DefaultChannelPromise.java:28)
        at net.minecraft.network.NetworkManager.func_150718_a(NetworkManager.java:302)
        at net.minecraft.network.NetworkSystem$7.operationComplete(NetworkSystem.java:204)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:680)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:603)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:563)
        at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:406)
        at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:82)
        at io.netty.channel.ChannelOutboundBuffer.safeSuccess(ChannelOutboundBuffer.java:523)
        at io.netty.channel.ChannelOutboundBuffer.remove(ChannelOutboundBuffer.java:247)
        at io.netty.channel.ChannelOutboundBuffer.removeBytes(ChannelOutboundBuffer.java:322)
        at io.netty.channel.epoll.EpollSocketChannel.writeBytesMultiple(EpollSocketChannel.java:212)
        at io.netty.channel.epoll.EpollSocketChannel.doWriteMultiple(EpollSocketChannel.java:364)
        at io.netty.channel.epoll.EpollSocketChannel.doWrite(EpollSocketChannel.java:317)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:707)
        at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:248)
        at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollOutReady(EpollSocketChannel.java:623)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:322)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
        at java.lang.Thread.run(Thread.java:745)

</pre>

**Comment by Fexcraft** [comment]
Might look into it when I fix my github client...

**Comment by Fexcraft** [comment]
Which is the client method that is supposedly called on server side?

**Comment by hunter688** [comment]
Minecraft.getMinecraft().currentScreen

**Comment by Fexcraft** [comment]
ye, I found it.

Might try to add a Side-check, when did the crash happen?

**Comment by hunter688** [comment]
Im added workaround:

if (world.isRemote) {
....

but idk if its ok.


When usig this workaround, no crashes anymore, but when press right mouse button to fire, nothing happens.

Maybe some incomplete client/server code.

**Comment by Fexcraft** [comment]
I didn't do any much in the gun-related code except a basic version update and a few fixes, most stuff is done by @TypicalDarkness .

If the compiled jar doesn't crash on a running server, than that fix you used works :P

**Comment by Fexcraft** [comment]
I guess I fixed my github client...
also added the world.isRemove check,
Idk about the rest.
