### ISSUE TITLE
Player joining without correct content pack crashes server

### ISSUE THREAD

**Issue by Bysokar** [Fexcraft/FlansMod#31]
Looks like when a player joins with the wrong content packs and is then kicked, FCL doesn't translate this into a 'do nothing' scenario and attempts to save data about the player. Using your latest 1.11.2 version with the FCL from the libs directory.

```
java.lang.NullPointerException: Saving entity NBT
        at net.fexcraft.mod.lib.perms.player.PlayerPerms.save(PlayerPerms.java:48)
        at net.fexcraft.mod.lib.perms.player.PlayerHandler$Provider.serializeNBT(PlayerHandler.java:54)
        at net.minecraftforge.common.capabilities.CapabilityDispatcher.serializeNBT(CapabilityDispatcher.java:123)
        at net.minecraft.entity.Entity.func_189511_e(Entity.java:1697)
        at net.minecraft.server.management.PlayerList.handler$onPlayerLogOut$zhm000(PlayerList.java:1974)
        at net.minecraft.server.management.PlayerList.func_72367_e(PlayerList.java)
        at net.minecraft.network.NetHandlerPlayServer.func_147231_a(NetHandlerPlayServer.java:795)
        at net.minecraft.network.NetworkManager.func_179293_l(NetworkManager.java:455)
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:213)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:743)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
        at java.lang.Thread.run(Thread.java:745)

****
```

**Comment by Fexcraft** [comment]
player perms is server side only :thinking: 
clientdata shouldn't matter, it's rather the old bug where new player's data crash on instant leave
I'll see the version.

**Comment by Bysokar** [comment]
Thanks @Fexcraft :)
None of the packs I have worked at all and FlansMod doesn't even have creative tabs on 1.11.2 - is that expected?

**Comment by Fexcraft** [comment]
:thinking: at least vehicles should show up.
I recall the tab .lang was not updated and they had the wrong name.
e.g. vehicle tab was called "Flansmod - Guns".
